#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>


#define MAX_MACRO_NAME_LEN  256
#define MAX_CACHE_FILE_PATH 512


static void _strToMacroName(char *buf, int len, const char *prefix,
                            const char *name, const char *suffix) {
    int pos;

    for(pos = 0; (pos < len) && (*prefix != '\0'); pos++) {
        buf[pos] = ((isalnum(*prefix)) ? toupper(*prefix) : '_');
        prefix++;
    }
    for(;(pos < len) && (*name != '\0'); pos++) {
        buf[pos] = ((isalnum(*name)) ? toupper(*name) : '_');
        name++;
    }
    for(;(pos < len) && (*suffix != '\0'); pos++) {
        buf[pos] = ((isalnum(*suffix)) ? toupper(*suffix) : '_');
        suffix++;
    }
    if(pos < len) {
    	buf[pos] = '\0';
    } else {
	    buf[len - 1] = '\0';
    }
}

static void textureCacheHeaderWrite(FILE *fp, const char *filename, const char *name) {
    char symbol[MAX_MACRO_NAME_LEN];

    _strToMacroName(symbol, sizeof(symbol), "_FLUB_CACHE_", name, "_HEADER_");

    fprintf(fp, "// Flub texture cache resource \"%s\"\n", name);
    fprintf(fp, "// Autogenerated from \"%s\"\n\n", filename);

    fprintf(fp, "#ifndef %s\n", symbol);
    fprintf(fp, "#define %s\n\n\n", symbol);

    fprintf(fp, "#include <flub/texture.h>\n\n\n");

    fprintf(fp, "extern char s_textureCache_%s_data[];\n", name);
    fprintf(fp, "extern textureCache_t s_textureCache_%s;\n\n\n", name);

    fprintf(fp, "#endif // %s\n\n", symbol);
}

static void textureCacheSourceWrite(FILE *fp, const char *filename,
                                    const char *header, const char *name,
                                    int colorkey, int red, int green, int blue,
                                    const char *minfilter, const char *magfilter,
                                    FILE *in) {
	int c;
    int len = 0;
    int pos = 0;
    char buf[32];

    if(minfilter == NULL) {
        minfilter = "0";
    }

    if(magfilter == NULL) {
        magfilter = "0";
    }

    fprintf(fp, "// Flub texture cache resource \"%s\"\n", name);
    fprintf(fp, "// Autogenerated from \"%s\"\n\n", filename);

    fprintf(fp, "#include \"%s\"\n\n", header);

    fprintf(fp, "char s_textureCache_%s_data[] = {", name);
    while((c = fgetc(in)) != EOF) {
        if(!(len % 16)) {
            if(pos > 0) {
                buf[pos] = '\0';
                fprintf(fp, " // %s\n    ", buf);
                pos = 0;
            } else {
                fprintf(fp, "\n    ");
            }
        }
        fprintf(fp, "0x%0.2x, ", c);
        buf[pos] = ((isprint(c) && (c > 32)) ? c : '.');
        pos++;
        len++;
    }
    fprintf(fp, "};\n\n");

    fprintf(fp, "textureCache_t s_textureCache_%s = {\n", name);
    fprintf(fp, "    .data      = s_textureCache_%s_data,\n", name);
    fprintf(fp, "    .size      = %d,\n", len);
    fprintf(fp, "    .name      = \"%s\",\n", name);
    fprintf(fp, "    .colorkey  = %c,\n", ((colorkey) ? '1' : '0'));
    fprintf(fp, "    .red       = %d,\n", red);
    fprintf(fp, "    .green     = %d,\n", green);
    fprintf(fp, "    .blue      = %d,\n", blue);
    fprintf(fp, "    .minfilter = %s,\n", minfilter);
    fprintf(fp, "    .magfilter = %s, };\n\n", magfilter);
}

int textureCacheBuild(const char *base, const char *filename, const char *name,
					  int colorkey, int red, int green, int blue,
                      const char *minfilter, const char *magfilter) {
    char buffer[MAX_CACHE_FILE_PATH];
    FILE *fp;
    FILE *in;
    char buf[1024];

    // Open the texture
    if((in = fopen(filename, "rb")) == NULL) {
        fprintf(stdout, "ERROR: Failed to open the file \"%s\". [%s]", filename, getcwd(buf, sizeof(buf)));
        return 0;
    }

    snprintf(buffer, sizeof(buffer), "%s.c", base);
    if((fp = fopen(buffer, "wt")) == NULL) {
        perror("WTF");
        fprintf(stdout, "ERROR: Failed to open the file \"%s\" for writing.", buffer);
        return 0;
    }
    snprintf(buffer, sizeof(buffer), "%s.h", base);
    textureCacheSourceWrite(fp, filename, buffer, name, colorkey, red, green, blue, minfilter, magfilter, in);
    fclose(in);
    fclose(fp);

    if((fp = fopen(buffer, "wt")) == NULL) {
        fprintf(stdout, "ERROR: Failed to open the file \"%s\" for writing.", buffer);
        return 0;
    }
    textureCacheHeaderWrite(fp, filename, name);
    fclose(fp);

    return 1;
}

void usage(void) {
	printf("texcache [options]\n\n");

	printf("    --path <output_file_path>\n");
	printf("    --image <image_file_path>\n");
	printf("    --name <symbolic_name>\n");
	printf("    --red <red_colorkey_value>\n");
	printf("    --green <green_colorkey_value>\n");
	printf("    --blue <blue_colorkey_value>\n");
	printf("    --minfilter <minfilter_gl_value>\n");
	printf("    --magfilter <magfilter_gl_value>\n");
	printf("\n");
}

int main(int argc, char *argv[]) {
	int pos;
	char *basepath = NULL;
	char *imgfile = NULL;
	char *name = "FlubCache";
	char *red = NULL;
	char *green = NULL;
	char *blue = NULL;
	char *minfilter = NULL;
	char *magfilter = NULL;
    char buf[1024];

	for(pos = 1; (pos < argc); pos += 2) {
		if(!strcmp(argv[pos], "--path")) {
			basepath = argv[pos + 1];
		} else if(!strcmp(argv[pos], "--image")) {
			imgfile = argv[pos + 1];
		} else if(!strcmp(argv[pos], "--name")) {
			name = argv[pos + 1];
		} else if(!strcmp(argv[pos], "--red")) {
			red = argv[pos + 1];
		} else if(!strcmp(argv[pos], "--green")) {
			green = argv[pos + 1];
		} else if(!strcmp(argv[pos], "--blue")) {
			blue = argv[pos + 1];
		} else if(!strcmp(argv[pos], "--minfilter")) {
			minfilter = argv[pos + 1];
		} else if(!strcmp(argv[pos], "--magfilter")) {
			magfilter = argv[pos + 1];
		} else {
			printf("ERROR: Unexpected parameter \"%s\".\n", argv[pos]);
			usage();
			return 1;
		}
	}

	if(basepath == NULL) {
		printf("ERROR: No base output path specified.\n");
		usage();
		return 1;
	}
	if(imgfile == NULL) {
		printf("ERROR: No image input file specified.\n");
		usage();
		return 1;
	}
	if(name == NULL) {
		printf("ERROR: No name specified.\n");
		usage();
		return 1;
	}

	if(!textureCacheBuild(basepath, imgfile, name,
						  (((red != NULL) || (green != NULL) || (blue != NULL)) ? 1 : 0),
						  ((red != NULL) ? atoi(red) : 0),
						  ((green != NULL) ? atoi(green) : 0),
						  ((blue != NULL) ? atoi(blue) : 0),
						  minfilter, magfilter)) {
		return 1;
	}

	printf("Texture cache source files generated:\n");
	printf(" *    %s.c\n", basepath);
	printf(" *    %s.h\n", basepath);
	printf("\n");

	return 0;
}
