#!/bin/sh

if [ -z "$1" ]; then
	export TODO_FILE="todo.txt"
else
	export TODO_FILE="$1"
fi

if [ -z "$2" ]; then
	export PATTERN="*"
else
	export PATTERN="$2"
fi

if [ -z "$3" ]; then
	export FLAGS="-r"
else
	export FLAGS="$3"
fi

echo "Generating todo file \"${TODO_FILE}\" from source comments in [${PATTERN}]..."
echo "todo.txt:0: This file is automatically generated by the make file, DO NOT EDIT." >${TODO_FILE}
echo "Calling with flags: [${FLAGS}]"
grep -n -I ${FLAGS} "TODO" ${PATTERN}|grep -v "todo\.sh"|grep -v "todo\.txt"|perl -pe 's/\s+/ /g; s/\/\/|\/\*|\*\///g; s/^(\w+\/?)+\///g; s/:[^\d].*TODO/: TODO/g; print "\n"' >>${TODO_FILE}
export count=`wc ${TODO_FILE}|perl -pe '$_=~s/^\s*(\d+)\s+.+$/$1/; $_ -= 1;'`
echo "Found ${count} TODO items within this project."
